spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 192.168.74.129
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: 1
      min-idle: 0
    timeout: 0

logging:
  level:
    com.gzyijian.mybatisredis.mapper: debug

# 打印自动配置报告
debug: true

# 开启驼峰命名匹配规则
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
